Sean cypress
Ctrl-Alt-GPT/BillSplitter-backend pull request #38
Opened 2023-10-11 16:54 UTC by Sean1783

Completes issues 20, 24, 32.

2023-10-12 17:31 UTC, andrewjunggg requested changes
Great work, Sean!
I can see your app is working on my end. However you might want to handle the user input validation for your TaxTips component. Also, if you want to enhance the remove item, that would be even better!

2023-10-16 16:32 UTC, andrewjunggg approved these changes

2023-10-16 16:32 UTC, andrewjujun commented on src/components/Items/Items.js
You might want to create remove item for each items in `Items` component. You can do the button on the `Item` component.

Essentially, when the user click that remove item button for a particular item, it will remove that item from the `items` array that we have on `Board` component.

2023-10-16 16:32 UTC, andrewjujun commented on src/components/TaxTipsAdd/TaxTipsAdd.js
You should handle input validation here just the way I did on the `Amount` input in `NewItemForm` component. This will prevent negative numbers and also set the form input to numbers only.

2023-10-16 16:33 UTC, merged