sean_cypress
Ctrl-Alt-GPT/BillSplitter-backend pull request #67
Opened 2023-10-29 22:39 UTC by Sean1783

Fixed 'remove' function. Added real-time tallying. Experimenting with displaying records on search.

2023-10-30 01:44 UTC, andrewjunggg requested changes
Hello Sean,
Don't forget to update the branch with the latest main!

2023-10-30 20:38 UTC, Sean1783 commented
> Hello Sean, Don't forget to update the branch with the latest main!
Thanks dude - should be all set now.

2023-10-31 00:39 UTC, andrewjunggg requested changes

2023-10-31 00:39 UTC, andrewjunggg commented on backend/index.js
Don't forget to change back to `*` so it works on the server!

2023-10-31 00:39 UTC, andrewjunggg commented on src/app/search/page.js
Same here!

2023-10-31 00:39 UTC, andrewjunggg commented on src/components/IndividualTotals/IndividualTotals.js
> +        'http://localhost:3333/sean/createBill'
Here too!

2023-10-31 22:12 UTC, andrewjunggg approved these changes
Looks good now.

2023-10-31 22:14 UTC, merged